### ISSUE TITLE
the .exe file is detected as Trojan Virus Why????

### ISSUE THREAD

**Issue by AliM1988** [99fk/Bat-To-Exe-Converter-Downloader#1]
Hi
After converting the batch(.bat) file to .exe file using Bat To Exe Converter, the .exe file is detected as Trojan Virus. Why???

The sample batch file:
```
@echo off
if exist "myexe.exe" START myexe.exe
Exit
```

I created an invisible 32 bit output. Once with UPX compression and once without it. Both of them are tested via VirusTotal.com. Over 25 AVs detected both as virus.

This is a false positive indeed. What is your solution?

Regard

**Comment by 99fk** [comment]
Do yo want me to open over 25 supported tickets and beg them to remove the false positives?

**Comment by AliM1988** [comment]
No, indeed. I wonder is any way to overcome this problem in next version or not.

**Comment by 99fk** [comment]
Modifications in the code would lower the amount of false positives .... for a few weeks.

In order to get "good results" on VirusTotal for an exe the user needs to open 25 support tickets ( a lot of patience and luck afterwars ) for each a new exe file generated.

Seriously, i don't know a convenient solution to solve the FP issues with these snakeoil vendors.

Sorry!
